spring:
  datasource:
    url: jdbc:h2:./kreitekfy;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    driverClassName: org.h2.Driver
  sql:
    init:
      mode: never
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  main:
    allow-circular-references: true
  h2:
    console:
      enabled: true
      path: /console

server:
  servlet:
    context-path: /kreitekfy
